name: Build Package

env:
  ENVIRONMENT_NAME: fork

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v[0-9].[0-9]+.[0-9]+
      - demo-v[0-9].[0-9]+.[0-9]+
      - staging-v[0-9].[0-9]+.[0-9]+
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - v[0-9].[0-9]+.[0-9]+
      - demo-v[0-9].[0-9]+.[0-9]+
      - staging-v[0-9].[0-9]+.[0-9]+

jobs:
  build_job:
    name: Build Fork
    if: github.repository_owner != 'rxlightning'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Instal Dependencies From Package Lock
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Test
      run: npm run test